#!/bin/bash

# PATHS ======================================================================
# MacPorts
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# Postgres path for psycopg2
export PATH=$PATH:/opt/local/lib/postgresql84/bin


# Prompt =====================================================================
source ~/.git-completion.bash

export PS1='\[\e[32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\W\[\e[0;33m\]$(__git_ps1 "(%s)")\[\e[0m\]\$ '


export WORKON_HOME=$HOME/.ve


# Bash completions ===========================================================
source /opt/local/bin/virtualenvwrapper_bashrc-2.6

_virtualenvs()
{
    PROJECTS=`(cd "$WORKON_HOME"; for f in */bin/activate; do echo $f; done) 2>/dev/null |
 sed 's|^\./||' | sed 's|/bin/activate||' | sort`
    local cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "$PROJECTS" -- ${cur}) )
}
complete -o default -o nospace -F _virtualenvs work


function work () {
    typeset env_name="$1"
    if [ "$env_name" = "" ]
    then
        virtualenvwrapper_show_workon_options
        return 1
    fi

    virtualenvwrapper_verify_workon_environment $env_name || return 1

    echo "source ~/.bash_profile
          workon $env_name
          cdvirtualenv
          cd src" > ~/.virtualenvrc

    bash --rcfile ~/.virtualenvrc
}
